import { expect, test } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { uiRoutes } from './routes';

for (const route of uiRoutes) {
  test.describe(`docs review: ${route.name}`, () => {
    test('renders without root overflow or serious accessibility violations', async ({ page }, testInfo) => {
      await page.goto(route.path, { waitUntil: 'domcontentloaded' });

      await expect(page.getByRole('heading', { level: 1, name: route.heading })).toBeVisible();
      // The Mintlify dev runtime keeps background requests open and can leave
      // document.readyState at "interactive". Give client-rendered MDX and
      // KaTeX two settled frames before measuring the final layout instead.
      await page.waitForTimeout(1_500);
      await page.evaluate(() => new Promise<void>((resolve) => {
        requestAnimationFrame(() => requestAnimationFrame(() => resolve()));
      }));

      if (route.name === 'tokenomics') {
        await expect(page.getByText('September 2027')).toBeVisible();
        await expect(page.getByText('139.522944 SAUCE/min', { exact: false })).toBeVisible();
        await expect(page.getByRole('link', { name: 'Community pools' })).toHaveCount(0);
      }
      if (route.name === 'wallet') {
        await expect(page.getByRole('heading', { name: 'Kabila Wallet' })).toBeVisible();
      }
      if (route.name === 'for-projects') {
        await expect(page.getByText('SaucerSwap checks token information frequently')).toBeVisible();
      }
      if (route.name === 'routing') {
        await expect(page.getByText('Split route.', { exact: true })).toBeVisible();
        const v3Link = page.locator('main a[href="/protocol/saucerswap-v3"]').first();
        await expect(v3Link).toBeVisible();
        await expect(v3Link).toHaveAttribute('href', '/protocol/saucerswap-v3');
      }

      const horizontalOverflow = await page.evaluate(() => {
        const root = document.documentElement;
        const body = document.body;
        const scrollWidth = Math.max(root.scrollWidth, body?.scrollWidth || 0);
        return scrollWidth > window.innerWidth + 1;
      });
      expect(
        horizontalOverflow,
        `${route.path} should not create root overflow in ${testInfo.project.name}`,
      ).toBe(false);

      const axe = await new AxeBuilder({ page })
        .withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'])
        // Mintlify's local preview misreports its dark theme background as white
        // emits an empty react-medium-image-zoom aria-owns target, and assigns
        // tabindex="-1" to its generated scrollable-table viewport. These are
        // generated by the preview runtime rather than this repository's MDX.
        .disableRules([
          'color-contrast',
          'aria-valid-attr-value',
          'scrollable-region-focusable',
        ])
        .analyze();
      const serious = axe.violations.filter(({ impact }) => impact === 'serious' || impact === 'critical');
      expect(serious).toEqual([]);

      await page.screenshot({
        path: testInfo.outputPath(`${route.name}-${testInfo.project.name}.png`),
        fullPage: true,
      });
    });
  });
}

test.describe('navigation regressions', () => {
  test('routes from the swap-routing guide to the V3 overview', async ({ page }) => {
    await page.goto('/protocol/routing', { waitUntil: 'domcontentloaded' });
    const v3Link = page.locator('main a[href="/protocol/saucerswap-v3"]').first();
    await expect(v3Link).toBeVisible();
    await v3Link.click();

    await expect(page).toHaveURL(/\/protocol\/saucerswap-v3$/);
    await expect(page.getByRole('heading', { level: 1, name: 'SaucerSwap V3' })).toBeVisible();
  });

  test('redirects the retired Community Pools route', async ({ page }) => {
    await page.goto('/protocol/community-pools', { waitUntil: 'domcontentloaded' });

    await expect(page).toHaveURL(/\/protocol\/overview$/);
    await expect(page.getByRole('heading', { level: 1, name: 'How SaucerSwap works' })).toBeVisible();
  });
});
